name: Test

on: [push]

env:
  ENVIRONMENT: ${{ github.event.action == 'prereleased' && 'staging' || 'production' }}
  DOCKER_POSTFIX: ${{ github.event.action == 'prereleased' && '-staging' || '' }}
  REPO_URL: ghcr.io
  REPO_PROJECT: swiftdrivecorp
  REPO_CONFIG: infra-deploy

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT }}
    steps:
      - name: Print github context
        run: echo '${{ vars.TEST }}'
