name: Test

on: [push]

permissions:
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: killmenot
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "github-test-staging"
          image-tags: "*alpha*"
          cut-off: 1m
          dry-run: true
