name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - fr
          - ru
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: environment

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: print inputs
        run: |
          INPUTS_JSON=$(echo '${{ toJSON(inputs) }}')
          echo "$INPUTS_JSON"

      - name: print github
        run: |
          GITHUB_JSON=$(echo '${{ toJSON(github) }}')
          echo "$GITHUB_JSON"

      - name: print vars
        run: |
          echo '${{ toJSON(vars) }}'
